### ISSUE TITLE
How to downloading only the video files

### ISSUE THREAD

**Issue by Youssouf7** [Jefidev/lsfb-dataset#15]
Is there a way to download only the video files? i have tried setting the landmarks=None, parameter but it still wants to download the landmarks.

**Comment by ppoitier** [comment]
There is a way! You just have to specify the correct parameters to the downloader like in the [examples](https://github.com/LSFB-Team/lsfb-dataset/blob/master/examples/download_example.ipynb).

```python
from lsfb_dataset import Downloader

downloader = Downloader(
    dataset='cont',
    destination="./destination/folder",
    include_cleaned_poses=False,
    include_videos=True,
)
downloader.download()
```

**Comment by complex777** [comment]
That works. thank you
