### ISSUE TITLE
Changing the label mapping process

### ISSUE THREAD

**Issue by Jefidev** [Jefidev/lsfb-dataset#16]
## Problem Statement

To provide a mapping between signs labels (str) and an index (int), the dataset relies on a `sign_to_index.csv`. This file contains two columns, the name of the sign (class) and an index. It is ordered from the most represented sign (sign with the highest number of instances) to the least common one. 

This file is used when creating the label mapping for a dataset. It is also used to easily filter the n most common labels when the `n_labels` parameter is provided. It is also convenient to be sure that the same label mapping is always used between experiments.

However, in its current form, the workflow prevents the user from freely create a custom split for the dataset. Indeed, if a user want to exclude some sign for its experiments (i.e., keep only the signs present in an existing lexic), the straightforward solution is to filter the unwanted signs from the existing train and test split. Thus, the user could chose the split he want to use when loading the dataset. 

As the label mapping creation step relies on a `sign_to_index.csv` file that includes the labels filtered by the user in its custom split, the label mapping generated will include signs that are not relevant for the user. Even worth, if the user specifies the number of labels to keep (with `n_labels`), as the current `load_labels` function solely relies on the `sign_to_index.csv` file, some labels of interest for the user might be drop in profit of more frequent label in the overall dataset. 

To avoid this issue the way of processing labels must be changed.

## Solution 1: Adding a config parameter (preferred)

The straightforward solution would be to allow the user to specify his own sign-to-index mapping file that would be used to filter signs. It is easy to implement but would require more pre-processing work for the user of our library.

## Solution 2: Infer the label mapping at runtime

Instead of using the `sign_to_index.csv` as a source of truth for the labels to consider, it could be possible to infer the label mapping based on the instances present in the split. This solution would free the user from the creation of a custom label mapping file but it could create other hazards. For instance, a label mapping computed for the test split could not be the same as the label mapping computed on the train split if some signs are not present in the two sets.

I am open to your critics and other way to solve this issue.

**Comment by ppoitier** [comment]
I also think that allowing the user to specify his own sign-to-index mapping file is a good idea and is quite straightforward.
It also possible to include a black list of labels in addition of the label mapping.
Would this solution be sufficient to resolve this problem?

To be honest, I prefer not to infer the label mapping at runtime as this would pose additional difficulties.

**Comment by Jefidev** [comment]
Allowing the user to provide its own sign-to-index is 20 lines of code.

Adding the "black list" mechanism would probably be a bit more cumbersome.
